/**
 * Message types supported by the Letta API.
 */
export enum MessageType {
  System = "system_message",
  User = "user_message",
  Reasoning = "reasoning_message",
  ToolCall = "tool_call_message",
  ToolReturn = "tool_return_message",
  Assistant = "assistant_message",
}

/**
 * Base interface for all message types.
 * Includes common properties like `id` and `date`.
 */
interface MessageBase {
  id?: string; // The unique identifier for the message (optional).
  date?: string; // The timestamp when the message was created (ISO format, optional).
}

/**
 * Represents a system-generated message.
 */
interface SystemMessage extends MessageBase {
  message_type: MessageType.System; // Indicates this is a system message.
  message: string; // The content of the system message.
}

/**
 * Represents a message sent by the user.
 */
interface UserMessage extends MessageBase {
  message_type: MessageType.User; // Indicates this is a user message.
  message: string; // The content of the user message.
}

/**
 * Represents an agent's internal reasoning.
 */
interface ReasoningMessage extends MessageBase {
  message_type: MessageType.Reasoning; // Indicates this is a reasoning message.
  reasoning: string; // The internal reasoning of the agent.
}

/**
 * Represents the function details within a tool call.
 */
interface ToolCallFunction {
  name: string; // The name of the function to call.
  arguments: string; // The arguments to pass to the function (JSON dump).
}

/**
 * Represents a tool call requested by the LLM.
 */
// interface ToolCall {
//   id: string; // The unique identifier for the tool call.
//   function: ToolCallFunction; // The function details for the tool call.
//   type?: string; // The type of the tool call (defaults to "function").
//   tool_call_id?: string; // The unique identifier for the tool call (optional).
// }

/**
 * Represents a delta update for a tool call (partial updates).
 */
export interface ToolCallDelta {
  name?: string; // The name of the function (optional).
  arguments?: string; // The arguments for the function (optional).
  tool_call_id?: string; // The unique identifier for the tool call (optional).
}

/**
 * Represents a message containing a tool call request.
 */
interface ToolCallMessage extends MessageBase {
  message_type: MessageType.ToolCall; // Indicates this is a tool call message.
  tool_call: ToolCallDelta; // The tool call details.
}

/**
 * Represents the return value of a tool call.
 */
interface ToolReturnMessage extends MessageBase {
  message_type: MessageType.ToolReturn; // Indicates this is a tool return message.
  status: "success" | "error"; // The status of the tool call (success or error).
  tool_call_id: string; // The unique identifier for the tool call.
  tool_return: string; // The return value of the tool.
  stderr?: string[]; // Captured stderr output from the tool invocation (optional).
  stdout?: string[]; // Captured stdout output from the tool invocation (optional).
}

/**
 * Represents a message generated by the assistant.
 */
interface AssistantMessage extends MessageBase {
  message_type: MessageType.Assistant; // Indicates this is an assistant message.
  assistant_message: string; // The content of the assistant message.
}

/**
 * Union type representing any type of message.
 */
export type LettaMessage =
  | SystemMessage
  | UserMessage
  | ReasoningMessage
  | ToolCallMessage
  | ToolReturnMessage
  | AssistantMessage;

/**
 * Represents a successful API response of the Get Agent Messages API.
 */
export interface GetAgentMessagesApiResponse {
  role: "assistant" | "user" | "tool" | "function" | "system"; // The role of the participant.
  created_by_id?: string; // The ID of the user who created the object (optional).
  last_updated_by_id?: string; // The ID of the user who last updated the object (optional).
  created_at?: string; // The timestamp when the object was created (ISO format, optional).
  updated_at?: string; // The timestamp when the object was last updated (ISO format, optional).
  id?: string; // The human-friendly ID of the message (optional, format: "^message-[a-fA-F0-9]{8}").
  text?: string; // The text content of the message (optional).
  agent_id?: string; // The unique identifier of the agent (optional).
  model?: string; // The model used to make the function call (optional).
  name?: string; // The name of the participant (optional).
  tool_calls?: ToolCall[]; // A list of tool calls requested (optional).
  messages?: LettaMessage[]; // A list of messages (optional).
}
